#!/bin/bash /etc/rc.common
START=99

run_autoupdate() {
  local enable
  config_get_bool enable $1 enable
  if [ $enable == "1" ]; then
    local minute
    local hour
    config_get week $1 week
    config_get minute $1 minute
    config_get hour $1 hour

    [ "${minute}" == "0" ] && minute="00"
    [ "${week}" == "7" ] && week="*"
    sed -i '/Romupdate/d' /etc/crontabs/root >/dev/null 2>&1
    echo "$minute $hour * * $week bash /bin/Romupdate.sh -u" >>/etc/crontabs/root
  else
    sed -i '/Romupdate/d' /etc/crontabs/root >/dev/null 2>&1
  fi
  if [ -f /bin/Romupdate.sh ] && [ -f /etc/openwrt_info ]; then
    custom_github_url="$(uci get romupdate.@login[0].github)"
    if [[ ! -z "${custom_github_url}" ]]; then
      current_github_url="$(cat /etc/openwrt_info | awk 'NR==2')"
      sed -i "s?${current_github_url}?${custom_github_url}?g" /etc/openwrt_info >/dev/null 2>&1
    fi
  fi
  /etc/init.d/cron restart
  echo "已重启 Romupdate 服务."
}

start() {
  config_load romupdate
  config_foreach run_autoupdate login
}

stop() {
  sed -i '/Romupdate/d' /etc/crontabs/root >/dev/null 2>&1
  echo "已停止 Romupdate 服务."
}

restart() {
  stop
  start
}
